[package]
name = "jddf-codegen"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
jddf = "0.3"
failure = "0.1"
serde_json = "1.0"
Inflector = "0.11"
